# Node and cluster
node.name: es01
discovery.type: single-node

# Security / passwords
# Note: ELASTIC_PASSWORD is usually set as env var, not in YAML, but you can reference it if needed
# xpack.security.enabled: true will require elastic password to be set via environment
xpack.security.enabled: true

# Bootstrap settings
bootstrap.memory_lock: true

# HTTP SSL
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.key: certs/es01/es01.key
xpack.security.http.ssl.certificate: certs/es01/es01.crt
xpack.security.http.ssl.certificate_authorities: ["certs/ca/ca.crt"]

# Transport SSL (for inter-node communication)
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.key: certs/es01/es01.key
xpack.security.transport.ssl.certificate: certs/es01/es01.crt
xpack.security.transport.ssl.certificate_authorities: ["certs/ca/ca.crt"]
xpack.security.transport.ssl.verification_mode: certificate

# License
xpack.license.self_generated.type: basic
