networks:
  siem-ng:
    external: true

volumes:
  certs:
    external: true
  fleetserverdata:
    driver: local

services:
  fleet-server:
    build:
      context: .
      args:
        ELASTIC_VERSION: ${STACK_VERSION}
    container_name: fleet-server
    volumes:
      - certs:/certs
      - fleetserverdata:/usr/share/elastic-agent
      # Only when monitoring containers with fleet policy
      # - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      # - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # Use only on production ubuntu monitoring
      # https://www.elastic.co/docs/reference/integrations/system
      # - "/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro"
      # - "/proc:/hostfs/proc:ro"
      # - "/:/hostfs:ro"
    ports:
      - 8220:8220
    user: root
    environment:
      - SSL_CERTIFICATE_AUTHORITIES=/certs/ca/ca.crt
      - CERTIFICATE_AUTHORITIES=/certs/ca/ca.crt
      - FLEET_CA=/certs/ca/ca.crt
      - FLEET_ENROLL=1
      - FLEET_INSECURE=true
      - FLEET_SERVER_ELASTICSEARCH_CA=/certs/ca/ca.crt
      - FLEET_SERVER_ELASTICSEARCH_HOST=https://es01:9200
      - FLEET_SERVER_ELASTICSEARCH_INSECURE=true
      - FLEET_SERVER_ENABLE=1
      - FLEET_SERVER_CERT=/certs/fleet-server/fleet-server.crt
      - FLEET_SERVER_CERT_KEY=/certs/fleet-server/fleet-server.key
      - FLEET_SERVER_INSECURE_HTTP=true
      - FLEET_SERVER_POLICY_ID=fleet-server-policy
      - FLEET_URL=https://fleet-server:8220
      - KIBANA_FLEET_CA=/certs/ca/ca.crt
      - KIBANA_FLEET_SETUP=1
      - KIBANA_FLEET_USERNAME=${KIBANA_FLEET_USERNAME}
      - KIBANA_FLEET_PASSWORD=${KIBANA_FLEET_PASSWORD}
      - KIBANA_HOST=${KIBANA_HOST}
    networks:
      - siem-ng
